# Generated by Django 2.1.2 on 2018-10-26 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_execution_time', models.FloatField()),
                ('avg_generations', models.IntegerField(default=0)),
                ('iterations', models.IntegerField(default=0)),
                ('word_length', models.IntegerField(default=0)),
                ('population_size', models.IntegerField(default=0)),
                ('mutations', models.IntegerField(default=0)),
                ('num_of_breeders', models.IntegerField(default=0)),
                ('fit_breeders', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='parent_graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizations.Graph'),
        ),
    ]
